# Generated by Django 5.0.6 on 2024-05-24 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 24, 4, 40, 11, 196302, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
